### ISSUE TITLE
Add enabled to vm binding

### ISSUE THREAD

**Issue by peonmodel** [convexset/meteor-three-way#1]
currently there is only binding for disabled, but none for enabled
say i have 2 elements, for the same boolean value, one needs to be enabled and the other visible

i would like to use the same function to set both

however as there is no enabled binding, only disabled binding, i would be required to create another function just to be the negator for the disabled binding

http://stackoverflow.com/questions/7708184/why-attribute-disabled-but-not-enabled

**Comment by convexset** [comment]
try data-bind="disabled: field|not"

**Comment by convexset** [comment]
https://github.com/convexset/meteor-three-way/blob/master/README.md#extradefault-pre-processors
