### ISSUE TITLE
get binding key

### ISSUE THREAD

**Issue by peonmodel** [convexset/meteor-three-way#4]
so i have a binding like this
```
data-bind="class:{error: givenname|validateEntry}"
data-bind="visible: familyname|validateEntry"
```
i can obtain the current value of familyname/givenname but
i would also require the string 'givenname', 'familyname' so that i know exactly which field the element is bound to, whether it is family name or givenname
 how should i do so

**Comment by convexset** [comment]
Done in: https://github.com/convexset/meteor-three-way/commit/9d00d8e5b00fe8af61ebfe724005977d090947d6
