### ISSUE TITLE
[Feature] viewModelToViewOnly.reset()

### ISSUE THREAD

**Issue by Anima-t3d** [convexset/meteor-three-way#5]
I would like to be able to call a reset() so that the `viewModelToViewOnly` resets to initial values.

Given:
```javascript
viewModelToViewOnly: {
    'label': '',
    'color': '',
    'user': 'The retrieved userId'
},
```

After doing data manipulation and add to server, I want to repopulate the data in the view with the defaults as defined above by simply calling a `.reset()`

Thanks!

**Comment by convexset** [comment]
See: https://github.com/convexset/meteor-three-way/commit/d90ac14efabb8742136067fc62d1ae1be3dd5d40
