### ISSUE TITLE
[Documentation] Update required in DEBUG section

### ISSUE THREAD

**Issue by Anima-t3d** [convexset/meteor-three-way#7]
## In doc list only
In [doc](https://github.com/convexset/meteor-three-way#debug) only: `["data", "default", "html", "new", "visible", "vm"]`
## In actual array list only
In actual `ThreeWay.DEBUG_MODE.MESSAGE_HEADINGS` only: `["new-id", "default-values", "data-mirror", "vm-only", "html-text", "visible-and-disabled", "process"]`
## Present in both, no need to update
`["parse", "bind", "tracker", "observer", "db", "validation", "reload", "bindings", "value", "checked", "focus", "style", "attr", "class", "event"]`

**Comment by convexset** [comment]
already done
