### ISSUE TITLE
[Feature] Change updatersForServer to read by default all document properties

### ISSUE THREAD

**Issue by Anima-t3d** [convexset/meteor-three-way#8]
It seems to me more sensible to only need to declare fields with updater in `updatersForServer` when actually wanting to also be able to update it easily. Most often I just want to read most properties from the document, but only a few I actually want to instantly bind threeway style.

Given:
```javascript
updatersForServer: {
	'title': 'updaterForTitle',
        // properties below this line I just need to be able to read
	'author': function () {},
	'date': function () {}
},
```
Desired:
```javascript
updatersForServer: {
	'title': 'updaterForTitle'
},
```

Thanks!

**Comment by convexset** [comment]
alt solution: read from document as "last resort"
